version: 2

before:
  hooks:
    - go mod tidy

builds:
  - main: .
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X github.com/QYVORA/qyvora-anansi/cmd.Version={{ .Version }}
    env:
      - CGO_ENABLED=0
    flags:
      - -trimpath

archives:
  - formats: [binary]
    name_template: "{{ .ProjectName }}-{{ .Os }}-{{ .Arch }}"

checksum:
  name_template: "checksums.txt"
  algorithm: sha256

release:
  github:
    owner: QYVORA
    name: qyvora-anansi
  prerelease: auto

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
